/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiPublicEmailBookingConfirmationRouteImport } from './routes/api/public/email/booking-confirmation'
import { Route as ApiPublicEmailConsultationRouteImport } from './routes/api/public/email/consultation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailBookingConfirmationRoute =
  ApiPublicEmailBookingConfirmationRouteImport.update({
    id: '/api/public/email/booking-confirmation',
    path: '/api/public/email/booking-confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmailConsultationRoute =
  ApiPublicEmailConsultationRouteImport.update({
    id: '/api/public/email/consultation',
    path: '/api/public/email/consultation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/public/email/booking-confirmation': typeof ApiPublicEmailBookingConfirmationRoute
  '/api/public/email/consultation': typeof ApiPublicEmailConsultationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/public/email/booking-confirmation': typeof ApiPublicEmailBookingConfirmationRoute
  '/api/public/email/consultation': typeof ApiPublicEmailConsultationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/public/email/booking-confirmation': typeof ApiPublicEmailBookingConfirmationRoute
  '/api/public/email/consultation': typeof ApiPublicEmailConsultationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/api/public/email/booking-confirmation'
    | '/api/public/email/consultation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/api/public/email/booking-confirmation'
    | '/api/public/email/consultation'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/api/public/email/booking-confirmation'
    | '/api/public/email/consultation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  ApiPublicEmailBookingConfirmationRoute: typeof ApiPublicEmailBookingConfirmationRoute
  ApiPublicEmailConsultationRoute: typeof ApiPublicEmailConsultationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/booking-confirmation': {
      id: '/api/public/email/booking-confirmation'
      path: '/api/public/email/booking-confirmation'
      fullPath: '/api/public/email/booking-confirmation'
      preLoaderRoute: typeof ApiPublicEmailBookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/consultation': {
      id: '/api/public/email/consultation'
      path: '/api/public/email/consultation'
      fullPath: '/api/public/email/consultation'
      preLoaderRoute: typeof ApiPublicEmailConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  ApiPublicEmailBookingConfirmationRoute:
    ApiPublicEmailBookingConfirmationRoute,
  ApiPublicEmailConsultationRoute: ApiPublicEmailConsultationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
